@key=key1

POST http://localhost:3500/v1.0/state/pluggable-supabase
Content-Type: application/json

[
    {
        "key": "{{key}}",
        "value": "This is stored in Supabase!"
    }
]

###
GET http://localhost:3500/v1.0/state/pluggable-supabase/{{key}}

###
DELETE http://localhost:3500/v1.0/state/pluggable-supabase/{{key}}